"""initial schema

Revision ID: fb6eae330c65
Revises:
Create Date: 2026-09-29 23:52:37.527942

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb6eae330c65"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repositories_external_id"), "repositories", ["external_id"], unique=True
    )
    op.create_table(
        "merge_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("source_branch", sa.String(length=255), nullable=False),
        sa.Column("target_branch", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merge_requests_external_id"), "merge_requests", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_merge_requests_repository_id"), "merge_requests", ["repository_id"], unique=False
    )
    op.create_table(
        "review_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merge_request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="reviewjobstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["merge_request_id"], ["merge_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_jobs_merge_request_id"), "review_jobs", ["merge_request_id"], unique=False
    )
    op.create_table(
        "context_payloads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_job_id", sa.Uuid(), nullable=False),
        sa.Column("diff_text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=100), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_job_id"], ["review_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_payloads_review_job_id"),
        "context_payloads",
        ["review_job_id"],
        unique=True,
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_job_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO", "WARNING", "ERROR", "CRITICAL", name="findingseverity", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_job_id"], ["review_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_review_job_id"), "findings", ["review_job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_findings_review_job_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_context_payloads_review_job_id"), table_name="context_payloads")
    op.drop_table("context_payloads")
    op.drop_index(op.f("ix_review_jobs_merge_request_id"), table_name="review_jobs")
    op.drop_table("review_jobs")
    op.drop_index(op.f("ix_merge_requests_repository_id"), table_name="merge_requests")
    op.drop_index(op.f("ix_merge_requests_external_id"), table_name="merge_requests")
    op.drop_table("merge_requests")
    op.drop_index(op.f("ix_repositories_external_id"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###
